name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Stop existing PM2 process
      run: pm2 stop eve-online-market-browser || true

    - name: Start application with PM2
      run: pm2 start backend/server.js --name eve-online-market-browser

    - name: Save PM2 process list
      run: pm2 save

    - name: Setup PM2 startup script
      run: pm2 startup